const CategoryObj: Record<string, string> = {
    "adventure": "adventure",
    "fantasy": "fantasy",
    "animation": "animation",
    "drama": "drama",
    "horror": "horror",
    "action": "action",
    "comedy": "comedy",
    "history": "history",
    "western": "western",
    "thriller": "thriller",
    "crime": "crime",
    "documentary": "documentary",
    "science fiction": "science fiction",
    "mystery": "mystery",
    "music": "music",
    "romance": "romance",
    "family": "family",
    "war": "war",
    "tv movie": "tv movie",
    "приключения": "adventure",
    "фэнтези": "fantasy",
    "мультфильм": "animation",
    "драма": "drama",
    "ужасы": "horror",
    "боевик": "action",
    "комедия": "comedy",
    "история": "history",
    "вестерн": "western",
    "триллер": "thriller",
    "криминал": "crime",
    "документальный": "documentary",
    "фантастика": "science fiction",
    "детектив": "mystery",
    "музыка": "music",
    "мелодрама": "romance",
    "семейный": "family",
    "военный": "war",
    "телевизионный фильм": "tv movie",
}

export const stabilizerEnURL = (name: string): string => {
 return  CategoryObj[name]
}